### ISSUE TITLE
ErrorException in Filesystem.php line 81: file_put_contents

### ISSUE THREAD

**Issue by CrushCandy** [LansanaCamara/Medium#4]
file_put_contents(C:\Users\Mark\Desktop\Medium\storage\framework/sessions/117a97bcbdffb382e3ab076b76abdd5d1b9fa49b): failed to open stream: No such file or directory

Any ideas on this, fresh install.

**Comment by CrushCandy** [comment]
Windows 8 OS, seems to be possible write permissions, will check it out.

First project out of 8 to have this issue.

**Comment by LansanaCamara** [comment]
Hey Candy, there may be missing directories in the storage directory. I had
that problem once when I deleted the cached files in there, so had to
manually re-add them. Don't know why it's occurring though, will check out
when I get home

**Comment by CrushCandy** [comment]
Creating a sessions folder fixed the issue. Will create a pull request for fix.
